### ISSUE TITLE
Proposal: protect the master branch

### ISSUE THREAD

**Issue by drzax** [abcnews/covid19-data-import-function#47]
Github will now let us [protect branches](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches) in a variety of ways. For this repository I propose we turn on branch protection for `master` to avoid an accidental deploy.

I propose we require a pull request with at least two approvals before a merge is allowed.

Let me know what you think.

**Comment by katiaeirin** [comment]
Branch protection sounds good. 

Do you think we need approvals to merge though? I expect most reviews for this repo will be "Looks good if it works" given the purpose of the repo. 

A lot of merges are also for issues caused by third party changes and I imagine we want to merge those without having to wait a few days for a review.

**Comment by phocks** [comment]
Yep. As discussed in the dev chat. Agree with protecting the master branch from direct pushes. But maybe for ease, just because most of the pull requests will be for quick fixes, there is less need for approvals before a merge can happen.

**Comment by drzax** [comment]
I've turned this on now. Commits to master should have to go through a PR.
